import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div>
          <ul>
              <li>Concert Project</li>
              <li><Link href={"/home"}> Home </Link></li>
              <li><Link href={"/profile/ownerview"}> Profile </Link></li>
              <li><Link href={"/login"}> Login </Link></li>
              <li><Link href={"/list"}> Members </Link></li>
          </ul>
      </div>
        {children}
      </body>
    </html>
  );
}
